#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Rebuild paper figures recovered from historical temporary plot commands.

These figures were originally generated by one-off Kilo/Agent shell commands
instead of checked-in Python scripts. This file preserves the recovered
commands as maintainable plotting functions.

Recovered command source:
- /root/.local/share/kilo/kilo.db, table part
- rq4_efficiency: prt_e4af84b2400299XfsnvjAuYsJ5
- statement_rq3: prt_e500f5244002n9MuOmq1EEA8nG
- statement_ablation: prt_e50119d96002tkoKeRaYQ3j7FY
- rq3_ablation: prt_e503436b80029QQWT8vZ8FXyZj
- rq3_statement_ablation: prt_e5050cd14002s5OdSiEBYgqCXP
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Callable, Iterable, Sequence

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
FIG_DIR = ROOT / "ranker" / "results" / "figures"

METRICS = ["Top-1", "Top-5", "Top-10", "MAR", "MFR"]

BLUE = "#2196F3"
ORANGE = "#FF9800"
GRAY = "#9E9E9E"
GREEN = "#2E7D32"
RED = "#E53935"
PURPLE = "#7E57C2"

RQ3_STANDALONE_FIGSIZE = (6.4, 4.6)
RQ3_AXIS_LABEL_FONTSIZE = 18
RQ3_X_TICK_FONTSIZE = 16
RQ3_Y_TICK_FONTSIZE = 14
RQ3_ANNOTATION_FONTSIZE = 12.5
RQ3_LEGEND_FONTSIZE = 11.5
RQ3_STANDALONE_MARGINS = {
    "left": 0.205,
    "right": 0.985,
    "top": 0.97,
    "bottom": 0.17,
}


def save_figure(
    fig: plt.Figure,
    stem: str,
    dpi: int = 300,
    bbox_inches: str | None = "tight",
) -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    save_kwargs = {}
    if bbox_inches is not None:
        save_kwargs["bbox_inches"] = bbox_inches
    fig.savefig(FIG_DIR / f"{stem}.png", dpi=dpi, **save_kwargs)
    fig.savefig(FIG_DIR / f"{stem}.pdf", **save_kwargs)
    plt.close(fig)
    print(f"[OK] Saved {FIG_DIR / (stem + '.png')} and .pdf")


def improvement_values(
    proposed: Sequence[float],
    baseline: Sequence[float],
    floor: float | None = None,
) -> list[float]:
    values: list[float] = []
    for idx, (p_value, b_value) in enumerate(zip(proposed, baseline)):
        if idx < 3:
            value = (p_value - b_value) / b_value * 100.0
        else:
            value = (b_value - p_value) / b_value * 100.0
        if floor is not None:
            value = max(value, floor)
        values.append(value)
    return values


def format_bar_value(value: float, decimal_for_rank: bool = True) -> str:
    if abs(value - round(value)) < 1e-9:
        return f"{value:.0f}"
    return f"{value:.1f}" if decimal_for_rank else f"{value:.2f}"


def annotate_grouped_bars(
    ax: plt.Axes,
    bars: Iterable[plt.Rectangle],
    formats: Sequence[str] | None = None,
    fontsize: float = 10,
) -> None:
    for idx, bar in enumerate(bars):
        height = bar.get_height()
        if formats is not None:
            label = formats[idx]
        else:
            label = format_bar_value(float(height))
        ax.annotate(
            label,
            xy=(bar.get_x() + bar.get_width() / 2, height),
            xytext=(0, 3),
            textcoords="offset points",
            ha="center",
            va="bottom",
            fontsize=fontsize,
            fontweight="bold",
            color="#333333",
        )


def plot_log_ablation(
    stem: str,
    cae: Sequence[float],
    wo_cae: Sequence[float],
    llm: Sequence[float],
    y_limit: tuple[float, float],
    y_ticks: Sequence[float],
    right_limit: tuple[float, float],
    right_ticks: Sequence[float],
    imp_wo_digits: int,
    bar_formats: tuple[Sequence[str], Sequence[str], Sequence[str]] | None = None,
) -> None:
    imp_wo = improvement_values(cae, wo_cae, floor=0.5)
    imp_llm = improvement_values(cae, llm, floor=0.5)

    fig, ax1 = plt.subplots(figsize=(12.8, 6.4))
    x = np.arange(len(METRICS))
    width = 0.25

    bars1 = ax1.bar(
        x + width,
        cae,
        width,
        label="CrashLocCAE",
        color=BLUE,
        edgecolor="white",
        linewidth=0.8,
    )
    bars2 = ax1.bar(
        x - width,
        wo_cae,
        width,
        label="w/o CAE Features",
        color=ORANGE,
        edgecolor="white",
        linewidth=0.8,
    )
    bars3 = ax1.bar(
        x,
        llm,
        width,
        label="LLM-Direct",
        color=GRAY,
        edgecolor="white",
        linewidth=0.8,
    )

    ax1.set_ylabel("Ranking Score", fontsize=17, fontweight="bold")
    ax1.set_xticks(x)
    ax1.set_xticklabels(METRICS, fontsize=16, fontweight="bold")
    ax1.tick_params(axis="y", labelsize=14)
    ax1.set_ylim(*y_limit)
    ax1.set_yticks(y_ticks)

    ax2 = ax1.twinx()
    ax2.set_yscale("log")
    (line1,) = ax2.plot(
        x,
        imp_wo,
        "D--",
        color=RED,
        linewidth=2.5,
        markersize=8,
        label="Imp. vs w/o CAE (%)",
    )
    (line2,) = ax2.plot(
        x,
        imp_llm,
        "s--",
        color=GREEN,
        linewidth=2.5,
        markersize=8,
        label="Imp. vs LLM-Direct (%)",
    )
    ax2.set_ylabel("")
    fig.text(
        0.965,
        0.52,
        "Improvement (%, log scale)",
        va="center",
        rotation="vertical",
        fontsize=17,
        fontweight="bold",
    )
    ax2.tick_params(axis="y", labelsize=14)
    ax2.set_ylim(*right_limit)
    ax2.yaxis.set_major_formatter(plt.ScalarFormatter())
    ax2.yaxis.set_minor_formatter(plt.NullFormatter())
    ax2.set_yticks(right_ticks)

    if bar_formats is None:
        annotate_grouped_bars(ax1, bars1, fontsize=12)
        annotate_grouped_bars(ax1, bars2, fontsize=12)
        annotate_grouped_bars(ax1, bars3, fontsize=12)
    else:
        annotate_grouped_bars(ax1, bars1, bar_formats[0], fontsize=12)
        annotate_grouped_bars(ax1, bars2, bar_formats[1], fontsize=12)
        annotate_grouped_bars(ax1, bars3, bar_formats[2], fontsize=12)

    red_offsets = [(0, 10), (0, 10), (0, 10), (-30, 14), (-30, 14)]
    green_offsets = [(0, -16), (0, -16), (0, -16), (30, -22), (30, -22)]
    for idx in range(len(METRICS)):
        ax2.annotate(
            f"{imp_wo[idx]:.{imp_wo_digits}f}%",
            xy=(x[idx], imp_wo[idx]),
            xytext=red_offsets[idx],
            textcoords="offset points",
            ha="center",
            fontsize=12,
            color=RED,
            fontweight="bold",
        )
        ax2.annotate(
            f"{imp_llm[idx]:.0f}%",
            xy=(x[idx], imp_llm[idx]),
            xytext=green_offsets[idx],
            textcoords="offset points",
            ha="center",
            fontsize=12,
            color=GREEN,
            fontweight="bold",
        )

    handles = [bars1, bars2, bars3, line1, line2]
    labels = [handle.get_label() for handle in handles]
    ax1.legend(
        handles,
        labels,
        loc="upper right",
        bbox_to_anchor=(0.985, 0.985),
        fontsize=10,
        frameon=True,
        framealpha=0.9,
        ncol=2,
    )

    plt.tight_layout()
    save_figure(fig, stem, dpi=300)


def plot_rq3_ablation() -> None:
    cae = [34, 37, 38, 9.8, 7.2]
    wo_module = [1, 2, 6, 4087.35, 3927.96]
    wo_cae = [21, 28, 31, 20.9, 17.2]
    llm = [3, 4, 4, 36.2, 33.2]

    imp_module = [3300, 1750, 533, 99, 99]
    imp_wo = [62, 32, 23, 53, 58]
    imp_llm = [1033, 825, 850, 73, 78]

    fig, ax1 = plt.subplots(figsize=(12.8, 6.4))
    x = np.arange(len(METRICS))
    width = 0.18

    bars_module = ax1.bar(
        x - 1.5 * width,
        wo_module,
        width,
        label="w/o Module Reduction",
        color=PURPLE,
        edgecolor="white",
        linewidth=0.8,
        hatch="//",
    )
    bars_wo_cae = ax1.bar(
        x - 0.5 * width,
        wo_cae,
        width,
        label="w/o CAE Features",
        color=ORANGE,
        edgecolor="white",
        linewidth=0.8,
    )
    bars_llm = ax1.bar(
        x + 0.5 * width,
        llm,
        width,
        label="LLM-Direct",
        color=GRAY,
        edgecolor="white",
        linewidth=0.8,
    )
    bars_cae = ax1.bar(
        x + 1.5 * width,
        cae,
        width,
        label="CrashLocCAE",
        color=BLUE,
        edgecolor="white",
        linewidth=0.8,
    )

    ax1.set_ylabel("Ranking Score (log scale)", fontsize=17, fontweight="bold")
    ax1.set_xticks(x)
    ax1.set_xticklabels(METRICS, fontsize=16, fontweight="bold")
    ax1.tick_params(axis="y", labelsize=14)
    ax1.set_yscale("log")
    ax1.set_ylim(0.8, 50000)
    ax1.set_yticks([1, 5, 10, 50, 100, 500, 1000, 5000, 10000, 50000])
    ax1.yaxis.set_major_formatter(plt.ScalarFormatter())
    ax1.yaxis.set_minor_formatter(plt.NullFormatter())

    annotate_grouped_bars(ax1, bars_module, ["1", "2", "6", "4087", "3928"], fontsize=12)
    annotate_grouped_bars(ax1, bars_wo_cae, ["21", "28", "31", "20.9", "17.2"], fontsize=12)
    annotate_grouped_bars(ax1, bars_llm, ["3", "4", "4", "36.2", "33.2"], fontsize=12)
    annotate_grouped_bars(ax1, bars_cae, ["34", "37", "38", "9.8", "7.2"], fontsize=12)

    ax2 = ax1.twinx()
    ax2.set_yscale("log")
    (line_module,) = ax2.plot(
        x,
        imp_module,
        "^--",
        color=PURPLE,
        linewidth=2.5,
        markersize=8,
        label="Imp. vs w/o Module (%)",
    )
    (line_wo,) = ax2.plot(
        x,
        imp_wo,
        "D--",
        color=RED,
        linewidth=2.5,
        markersize=8,
        label="Imp. vs w/o CAE (%)",
    )
    (line_llm,) = ax2.plot(
        x,
        imp_llm,
        "s--",
        color=GREEN,
        linewidth=2.5,
        markersize=8,
        label="Imp. vs LLM-Direct (%)",
    )
    ax2.set_ylabel("Improvement (%, log scale)", fontsize=17, fontweight="bold")
    ax2.tick_params(axis="y", labelsize=14)
    ax2.set_ylim(0.5, 10000)
    ax2.set_yticks([1, 5, 10, 50, 100, 500, 1000, 5000, 10000])
    ax2.yaxis.set_major_formatter(plt.ScalarFormatter())
    ax2.yaxis.set_minor_formatter(plt.NullFormatter())

    purple_offsets = [(0, 10), (0, 10), (-34, 10), (0, 12), (0, 12)]
    red_offsets = [(0, 8), (0, 8), (0, 8), (-28, 0), (-28, 0)]
    green_offsets = [(0, -12), (0, -12), (48, -8), (28, -8), (28, -8)]
    for idx in range(len(METRICS)):
        ax2.annotate(
            f"{imp_module[idx]}%",
            xy=(x[idx], imp_module[idx]),
            xytext=purple_offsets[idx],
            textcoords="offset points",
            ha="center",
            fontsize=12,
            color=PURPLE,
            fontweight="bold",
        )
        ax2.annotate(
            f"{imp_wo[idx]}%",
            xy=(x[idx], imp_wo[idx]),
            xytext=red_offsets[idx],
            textcoords="offset points",
            ha="center",
            fontsize=12,
            color=RED,
            fontweight="bold",
        )
        ax2.annotate(
            f"{imp_llm[idx]}%",
            xy=(x[idx], imp_llm[idx]),
            xytext=green_offsets[idx],
            textcoords="offset points",
            ha="center",
            fontsize=12,
            color=GREEN,
            fontweight="bold",
        )

    handles = [bars_module, bars_wo_cae, bars_llm, bars_cae, line_module, line_wo, line_llm]
    labels = [handle.get_label() for handle in handles]
    ax1.legend(
        handles,
        labels,
        loc="upper right",
        bbox_to_anchor=(0.985, 0.998),
        fontsize=9.8,
        frameon=True,
        framealpha=0.9,
        ncol=2,
    )

    fig.subplots_adjust(left=0.08, right=0.90, top=0.97, bottom=0.10)
    save_figure(fig, "rq3_ablation", dpi=300)


def plot_rq3_statement_ablation() -> None:
    cae = [26, 29, 32, 40.5, 14.8]
    wo_cae = [22, 24, 28, 48.5, 20.7]
    llm = [3, 7, 10, 88.5, 50.8]
    top_rank_formats = (
        ["26", "29", "32", "40.5", "14.8"],
        ["22", "24", "28", "48.5", "20.7"],
        ["3", "7", "10", "88.5", "50.8"],
    )
    plot_log_ablation(
        stem="rq3_statement_ablation",
        cae=cae,
        wo_cae=wo_cae,
        llm=llm,
        y_limit=(0, 120),
        y_ticks=[0, 20, 40, 60, 80, 100, 120],
        right_limit=(0.5, 1000),
        right_ticks=[1, 10, 100, 1000],
        imp_wo_digits=1,
        bar_formats=top_rank_formats,
    )


def plot_rq3_file_ranking_score() -> None:
    cae = [34, 37, 38, 9.8, 7.2]
    wo_module = [1, 2, 6, 4087.35, 3927.96]
    wo_cae = [21, 28, 31, 20.9, 17.2]
    llm = [3, 4, 4, 36.2, 33.2]

    fig, ax = plt.subplots(figsize=RQ3_STANDALONE_FIGSIZE)
    x = np.arange(len(METRICS))
    width = 0.18

    bars_module = ax.bar(
        x - 1.5 * width,
        wo_module,
        width,
        label="w/o Module Reduction",
        color=PURPLE,
        edgecolor="white",
        linewidth=0.8,
        hatch="//",
    )
    bars_wo_cae = ax.bar(
        x - 0.5 * width,
        wo_cae,
        width,
        label="w/o CAE Features",
        color=ORANGE,
        edgecolor="white",
        linewidth=0.8,
    )
    bars_llm = ax.bar(
        x + 0.5 * width,
        llm,
        width,
        label="LLM-Direct",
        color=GRAY,
        edgecolor="white",
        linewidth=0.8,
    )
    bars_cae = ax.bar(
        x + 1.5 * width,
        cae,
        width,
        label="CrashLocCAE",
        color=BLUE,
        edgecolor="white",
        linewidth=0.8,
    )

    ax.set_ylabel(
        "Ranking Score (log scale)",
        fontsize=RQ3_AXIS_LABEL_FONTSIZE,
        fontweight="bold",
    )
    ax.set_xticks(x)
    ax.set_xticklabels(METRICS, fontsize=RQ3_X_TICK_FONTSIZE, fontweight="bold")
    ax.set_xlim(-0.45, len(METRICS) - 0.55)
    ax.tick_params(axis="y", labelsize=RQ3_Y_TICK_FONTSIZE)
    ax.set_yscale("log")
    ax.set_ylim(0.8, 50000)
    ax.set_yticks([1, 5, 10, 50, 100, 500, 1000, 5000, 10000, 50000])
    ax.yaxis.set_major_formatter(plt.ScalarFormatter())
    ax.yaxis.set_minor_formatter(plt.NullFormatter())

    annotate_grouped_bars(
        ax,
        bars_module,
        ["1", "2", "6", "4087", "3928"],
        fontsize=RQ3_ANNOTATION_FONTSIZE,
    )
    annotate_grouped_bars(
        ax,
        bars_wo_cae,
        ["21", "28", "31", "20.9", "17.2"],
        fontsize=RQ3_ANNOTATION_FONTSIZE,
    )
    annotate_grouped_bars(
        ax,
        bars_llm,
        ["3", "4", "4", "36.2", "33.2"],
        fontsize=RQ3_ANNOTATION_FONTSIZE,
    )
    annotate_grouped_bars(
        ax,
        bars_cae,
        ["34", "37", "38", "9.8", "7.2"],
        fontsize=RQ3_ANNOTATION_FONTSIZE,
    )

    ax.legend(
        loc="upper left",
        bbox_to_anchor=(0.02, 0.98),
        fontsize=RQ3_LEGEND_FONTSIZE,
        frameon=True,
        framealpha=0.85,
        ncol=1,
        columnspacing=0.8,
        handletextpad=0.6,
        borderaxespad=0.0,
    )
    fig.subplots_adjust(**RQ3_STANDALONE_MARGINS)
    save_figure(fig, "rq3_file_ranking_score", dpi=300, bbox_inches=None)


def plot_rq3_file_improvement() -> None:
    imp_module = [3300, 1750, 533, 99, 99]
    imp_wo = [62, 32, 23, 53, 58]
    imp_llm = [1033, 825, 850, 73, 78]

    fig, ax = plt.subplots(figsize=RQ3_STANDALONE_FIGSIZE)
    x = np.arange(len(METRICS))

    ax.plot(
        x,
        imp_module,
        "^--",
        color=PURPLE,
        linewidth=2.8,
        markersize=9,
        label="vs w/o Module",
    )
    ax.plot(
        x,
        imp_wo,
        "D--",
        color=RED,
        linewidth=2.8,
        markersize=9,
        label="vs w/o CAE",
    )
    ax.plot(
        x,
        imp_llm,
        "s--",
        color=GREEN,
        linewidth=2.8,
        markersize=9,
        label="vs LLM-Direct",
    )

    ax.set_ylabel(
        "Improvement (%, log scale)",
        fontsize=RQ3_AXIS_LABEL_FONTSIZE,
        fontweight="bold",
    )
    ax.set_xticks(x)
    ax.set_xticklabels(METRICS, fontsize=RQ3_X_TICK_FONTSIZE, fontweight="bold")
    ax.set_xlim(-0.35, len(METRICS) - 0.55)
    ax.tick_params(axis="y", labelsize=RQ3_Y_TICK_FONTSIZE)
    ax.set_yscale("log")
    ax.set_ylim(8, 7000)
    ax.set_yticks([10, 50, 100, 500, 1000, 5000])
    ax.yaxis.set_major_formatter(plt.ScalarFormatter())
    ax.yaxis.set_minor_formatter(plt.NullFormatter())

    annotation_box = {"facecolor": "white", "edgecolor": "none", "alpha": 0.8, "pad": 0.2}
    purple_offsets = [(0, 12), (0, 12), (-18, -22), (-22, 12), (-22, 12)]
    red_offsets = [(0, -18), (0, -18), (0, -18), (0, -20), (0, -20)]
    green_offsets = [(0, -18), (0, -18), (24, 14), (28, -10), (28, -10)]
    for idx in range(len(METRICS)):
        ax.annotate(
            f"{imp_module[idx]}%",
            xy=(x[idx], imp_module[idx]),
            xytext=purple_offsets[idx],
            textcoords="offset points",
            ha="center",
            fontsize=RQ3_ANNOTATION_FONTSIZE,
            color=PURPLE,
            fontweight="bold",
            bbox=annotation_box,
        )
        ax.annotate(
            f"{imp_wo[idx]}%",
            xy=(x[idx], imp_wo[idx]),
            xytext=red_offsets[idx],
            textcoords="offset points",
            ha="center",
            fontsize=RQ3_ANNOTATION_FONTSIZE,
            color=RED,
            fontweight="bold",
            bbox=annotation_box,
        )
        ax.annotate(
            f"{imp_llm[idx]}%",
            xy=(x[idx], imp_llm[idx]),
            xytext=green_offsets[idx],
            textcoords="offset points",
            ha="center",
            fontsize=RQ3_ANNOTATION_FONTSIZE,
            color=GREEN,
            fontweight="bold",
            bbox=annotation_box,
        )

    ax.legend(
        loc="upper right",
        bbox_to_anchor=(0.98, 0.98),
        fontsize=RQ3_LEGEND_FONTSIZE,
        frameon=True,
        framealpha=0.85,
        ncol=1,
        columnspacing=0.8,
        handletextpad=0.5,
        borderaxespad=0.0,
    )
    fig.subplots_adjust(**RQ3_STANDALONE_MARGINS)
    save_figure(fig, "rq3_file_improvement", dpi=300, bbox_inches=None)


def plot_rq3_statement_ranking_score() -> None:
    cae = [26, 29, 32, 40.5, 14.8]
    wo_cae = [22, 24, 28, 48.5, 20.7]
    llm = [3, 7, 10, 88.5, 50.8]

    fig, ax = plt.subplots(figsize=RQ3_STANDALONE_FIGSIZE)
    x = np.arange(len(METRICS))
    width = 0.24

    bars_wo_cae = ax.bar(
        x - width,
        wo_cae,
        width,
        label="w/o CAE Features",
        color=ORANGE,
        edgecolor="white",
        linewidth=0.8,
    )
    bars_llm = ax.bar(
        x,
        llm,
        width,
        label="LLM-Direct",
        color=GRAY,
        edgecolor="white",
        linewidth=0.8,
    )
    bars_cae = ax.bar(
        x + width,
        cae,
        width,
        label="CrashLocCAE",
        color=BLUE,
        edgecolor="white",
        linewidth=0.8,
    )

    ax.set_ylabel("Ranking Score", fontsize=RQ3_AXIS_LABEL_FONTSIZE, fontweight="bold")
    ax.set_xticks(x)
    ax.set_xticklabels(METRICS, fontsize=RQ3_X_TICK_FONTSIZE, fontweight="bold")
    ax.set_xlim(-0.45, len(METRICS) - 0.55)
    ax.set_ylim(0, 105)
    ax.set_yticks([0, 20, 40, 60, 80, 100])
    ax.tick_params(axis="y", labelsize=RQ3_Y_TICK_FONTSIZE)

    annotate_grouped_bars(
        ax,
        bars_wo_cae,
        ["22", "24", "28", "48.5", "20.7"],
        fontsize=RQ3_ANNOTATION_FONTSIZE,
    )
    annotate_grouped_bars(
        ax,
        bars_llm,
        ["3", "7", "10", "88.5", "50.8"],
        fontsize=RQ3_ANNOTATION_FONTSIZE,
    )
    annotate_grouped_bars(
        ax,
        bars_cae,
        ["26", "29", "32", "40.5", "14.8"],
        fontsize=RQ3_ANNOTATION_FONTSIZE,
    )

    ax.legend(
        loc="upper left",
        bbox_to_anchor=(0.02, 0.98),
        fontsize=RQ3_LEGEND_FONTSIZE,
        frameon=True,
        framealpha=0.85,
        ncol=1,
        columnspacing=0.8,
        handletextpad=0.6,
        borderaxespad=0.0,
    )
    fig.subplots_adjust(**RQ3_STANDALONE_MARGINS)
    save_figure(fig, "rq3_statement_ranking_score", dpi=300, bbox_inches=None)


def plot_rq3_statement_improvement() -> None:
    cae = [26, 29, 32, 40.5, 14.8]
    wo_cae = [22, 24, 28, 48.5, 20.7]
    llm = [3, 7, 10, 88.5, 50.8]
    imp_wo = improvement_values(cae, wo_cae)
    imp_llm = improvement_values(cae, llm)

    fig, ax = plt.subplots(figsize=RQ3_STANDALONE_FIGSIZE)
    x = np.arange(len(METRICS))

    ax.plot(
        x,
        imp_wo,
        "D--",
        color=RED,
        linewidth=2.8,
        markersize=9,
        label="vs w/o CAE",
    )
    ax.plot(
        x,
        imp_llm,
        "s--",
        color=GREEN,
        linewidth=2.8,
        markersize=9,
        label="vs LLM-Direct",
    )

    ax.set_ylabel(
        "Improvement (%, log scale)",
        fontsize=RQ3_AXIS_LABEL_FONTSIZE,
        fontweight="bold",
    )
    ax.set_xticks(x)
    ax.set_xticklabels(METRICS, fontsize=RQ3_X_TICK_FONTSIZE, fontweight="bold")
    ax.set_xlim(-0.35, len(METRICS) - 0.55)
    ax.tick_params(axis="y", labelsize=RQ3_Y_TICK_FONTSIZE)
    ax.set_yscale("log")
    ax.set_ylim(8, 1300)
    ax.set_yticks([10, 50, 100, 500, 1000])
    ax.yaxis.set_major_formatter(plt.ScalarFormatter())
    ax.yaxis.set_minor_formatter(plt.NullFormatter())

    annotation_box = {"facecolor": "white", "edgecolor": "none", "alpha": 0.8, "pad": 0.2}
    red_offsets = [(0, -18), (0, -18), (0, -18), (-22, -8), (-22, -8)]
    green_offsets = [(0, 12), (0, 12), (0, 12), (24, 8), (24, 8)]
    for idx in range(len(METRICS)):
        ax.annotate(
            f"{imp_wo[idx]:.1f}%",
            xy=(x[idx], imp_wo[idx]),
            xytext=red_offsets[idx],
            textcoords="offset points",
            ha="center",
            fontsize=RQ3_ANNOTATION_FONTSIZE,
            color=RED,
            fontweight="bold",
            bbox=annotation_box,
        )
        ax.annotate(
            f"{imp_llm[idx]:.0f}%",
            xy=(x[idx], imp_llm[idx]),
            xytext=green_offsets[idx],
            textcoords="offset points",
            ha="center",
            fontsize=RQ3_ANNOTATION_FONTSIZE,
            color=GREEN,
            fontweight="bold",
            bbox=annotation_box,
        )

    ax.legend(
        loc="upper right",
        bbox_to_anchor=(0.98, 0.98),
        fontsize=RQ3_LEGEND_FONTSIZE,
        frameon=True,
        framealpha=0.85,
        ncol=1,
        columnspacing=0.8,
        handletextpad=0.5,
        borderaxespad=0.0,
    )
    fig.subplots_adjust(**RQ3_STANDALONE_MARGINS)
    save_figure(fig, "rq3_statement_improvement", dpi=300, bbox_inches=None)


def plot_statement_rq3() -> None:
    matplotlib.rcParams["font.family"] = "DejaVu Sans"

    crashloccae = [26.2, 28.8, 31.6, 40.51, 14.80]
    wo_cae = [26.0, 28.4, 31.4, 41.50, 15.04]
    crashloccae_std = [3.9, 3.5, 3.3, 7.21, 4.84]
    wo_cae_std = [4.3, 4.5, 3.5, 7.03, 5.27]

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    width = 0.35

    ax1 = axes[0]
    x = np.arange(3)
    bars1 = ax1.bar(
        x - width / 2,
        crashloccae[:3],
        width,
        yerr=crashloccae_std[:3],
        label="CrashLocCAE",
        color=BLUE,
        capsize=5,
        edgecolor="white",
        linewidth=0.8,
    )
    bars2 = ax1.bar(
        x + width / 2,
        wo_cae[:3],
        width,
        yerr=wo_cae_std[:3],
        label="w/o CAE Features",
        color=ORANGE,
        capsize=5,
        edgecolor="white",
        linewidth=0.8,
    )
    ax1.set_xlabel("Metric", fontsize=13)
    ax1.set_ylabel("Number of Bugs (hit count)", fontsize=13)
    ax1.set_title("Statement-Level RQ3: Top-N Comparison", fontsize=14, fontweight="bold")
    ax1.set_xticks(x)
    ax1.set_xticklabels(["Top-1", "Top-5", "Top-10"], fontsize=12)
    ax1.legend(fontsize=10, loc="upper right", ncol=2, frameon=True, framealpha=0.9)
    ax1.set_ylim(0, 40)
    ax1.grid(axis="y", alpha=0.3)
    annotate_statement_values(ax1, bars1, precision=1)
    annotate_statement_values(ax1, bars2, precision=1)

    ax2 = axes[1]
    x2 = np.arange(2)
    bars3 = ax2.bar(
        x2 - width / 2,
        crashloccae[3:],
        width,
        yerr=crashloccae_std[3:],
        label="CrashLocCAE",
        color=BLUE,
        capsize=5,
        edgecolor="white",
        linewidth=0.8,
    )
    bars4 = ax2.bar(
        x2 + width / 2,
        wo_cae[3:],
        width,
        yerr=wo_cae_std[3:],
        label="w/o CAE Features",
        color=ORANGE,
        capsize=5,
        edgecolor="white",
        linewidth=0.8,
    )
    ax2.set_xlabel("Metric", fontsize=13)
    ax2.set_ylabel("Rank (lower is better)", fontsize=13)
    ax2.set_title("Statement-Level RQ3: MAR / MFR", fontsize=14, fontweight="bold")
    ax2.set_xticks(x2)
    ax2.set_xticklabels(["MAR", "MFR"], fontsize=12)
    ax2.legend(fontsize=10, loc="upper right", ncol=2, frameon=True, framealpha=0.9)
    ax2.set_ylim(0, 110)
    ax2.grid(axis="y", alpha=0.3)
    annotate_statement_values(ax2, bars3, precision=2)
    annotate_statement_values(ax2, bars4, precision=2)

    delta_mar = wo_cae[3] - crashloccae[3]
    delta_mfr = wo_cae[4] - crashloccae[4]
    ax2.annotate(
        f"Delta = +{delta_mar:.2f}",
        xy=(0 + width / 2, wo_cae[3]),
        xytext=(0.3, wo_cae[3] + 10),
        fontsize=10,
        color="green",
        arrowprops=dict(arrowstyle="->", color="green", lw=1.5),
    )
    ax2.annotate(
        f"Delta = +{delta_mfr:.2f}",
        xy=(1 + width / 2, wo_cae[4]),
        xytext=(1.3, wo_cae[4] + 10),
        fontsize=10,
        color="green",
        arrowprops=dict(arrowstyle="->", color="green", lw=1.5),
    )

    plt.tight_layout()
    save_figure(fig, "statement_rq3", dpi=200)


def annotate_statement_values(ax: plt.Axes, bars: Iterable[plt.Rectangle], precision: int) -> None:
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2.0,
            height + 1.5,
            f"{height:.{precision}f}",
            ha="center",
            va="bottom",
            fontsize=10,
            fontweight="bold",
        )


def plot_statement_ablation() -> None:
    matplotlib.rcParams["font.family"] = "DejaVu Sans"

    crashloccae = [26.2, 28.8, 31.6, 40.51, 14.80]
    wo_cae = [26.0, 28.4, 31.4, 41.50, 15.04]
    llm_only = [3.4, 7.4, 9.8, 88.50, 50.80]

    imp_wo_cae = improvement_values(crashloccae, wo_cae)
    imp_llm = improvement_values(crashloccae, llm_only)

    fig, ax1 = plt.subplots(figsize=(12, 6))
    x = np.arange(5)
    width = 0.25

    bars1 = ax1.bar(
        x - width,
        crashloccae,
        width,
        label="CrashLocCAE",
        color=BLUE,
        edgecolor="white",
        linewidth=0.8,
        zorder=3,
    )
    bars2 = ax1.bar(
        x,
        wo_cae,
        width,
        label="w/o CAE Features",
        color=ORANGE,
        edgecolor="white",
        linewidth=0.8,
        zorder=3,
    )
    bars3 = ax1.bar(
        x + width,
        llm_only,
        width,
        label="LLM-Direct",
        color="#4CAF50",
        edgecolor="white",
        linewidth=0.8,
        zorder=3,
    )

    ax1.set_xlabel("Metric", fontsize=13)
    ax1.set_ylabel("Ranking / Metric Score", fontsize=13)
    ax1.set_xticks(x)
    ax1.set_xticklabels(METRICS, fontsize=12)
    ax1.set_ylim(0, 120)
    ax1.grid(axis="y", alpha=0.3, zorder=0)

    annotate_colored_values(ax1, bars1, "#1565C0")
    annotate_colored_values(ax1, bars2, "#E65100")
    annotate_colored_values(ax1, bars3, "#2E7D32")

    ax2 = ax1.twinx()
    ax2.plot(
        x,
        imp_wo_cae,
        marker="o",
        color=ORANGE,
        linewidth=2.5,
        markersize=8,
        label="Improvement vs w/o CAE",
        zorder=5,
        linestyle="--",
    )
    ax2.plot(
        x,
        imp_llm,
        marker="s",
        color="#4CAF50",
        linewidth=2.5,
        markersize=8,
        label="Improvement vs LLM-Direct",
        zorder=5,
        linestyle="--",
    )
    ax2.set_ylabel("Improvement (%)", fontsize=13)
    ax2.set_ylim(-10, 1200)

    for idx in range(5):
        ax2.annotate(
            f"{imp_wo_cae[idx]:+.1f}%",
            xy=(x[idx], imp_wo_cae[idx]),
            xytext=(0, 12),
            textcoords="offset points",
            ha="center",
            fontsize=9,
            color="#E65100",
            fontweight="bold",
        )
        ax2.annotate(
            f"{imp_llm[idx]:+.0f}%",
            xy=(x[idx], imp_llm[idx]),
            xytext=(0, 12),
            textcoords="offset points",
            ha="center",
            fontsize=9,
            color="#2E7D32",
            fontweight="bold",
        )

    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(
        lines1 + lines2,
        labels1 + labels2,
        fontsize=9,
        loc="upper right",
        bbox_to_anchor=(0.985, 0.985),
        ncol=2,
        frameon=True,
        framealpha=0.9,
    )

    plt.title("Statement-Level: CrashLocCAE vs Ablation Baselines", fontsize=14, fontweight="bold", pad=15)
    plt.tight_layout()
    save_figure(fig, "statement_ablation", dpi=200)


def plot_rq3_module_reduction_ablation(stem: str = "rq3_ablation") -> None:
    csv_path = ROOT / "ranker" / "results" / "rq3_module_reduction_ablation" / "summary.csv"
    rows: dict[str, dict[str, str]] = {}
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            rows[row["setting"]] = row

    module = rows["Full Model"]
    without = rows["w/o Module Reduction"]
    top_metrics = ["Top-1", "Top-5", "Top-10"]
    rank_metrics = ["MAR", "MFR"]
    module_top = [float(module["top1_hits"]), float(module["top5_hits"]), float(module["top10_hits"])]
    without_top = [float(without["top1_hits"]), float(without["top5_hits"]), float(without["top10_hits"])]
    module_rank = [float(module["mar"]), float(module["mfr"])]
    without_rank = [float(without["mar"]), float(without["mfr"])]

    fig, (ax_top, ax_rank) = plt.subplots(1, 2, figsize=(12.8, 6.4), gridspec_kw={"width_ratios": [1.2, 1.0]})
    width = 0.34

    x_top = np.arange(len(top_metrics))
    bars_without_top = ax_top.bar(
        x_top - width / 2,
        without_top,
        width,
        label="w/o Module Reduction",
        color=PURPLE,
        edgecolor="white",
        linewidth=0.8,
        hatch="//",
    )
    bars_module_top = ax_top.bar(
        x_top + width / 2,
        module_top,
        width,
        label="Full Model",
        color=BLUE,
        edgecolor="white",
        linewidth=0.8,
    )

    ax_top.set_ylabel("Hit Count", fontsize=14, fontweight="bold")
    ax_top.set_xticks(x_top)
    ax_top.set_xticklabels(top_metrics, fontsize=13, fontweight="bold")
    ax_top.tick_params(axis="y", labelsize=12)
    ax_top.set_ylim(0, 60)
    ax_top.set_yticks([0, 10, 20, 30, 40, 50, 60])
    ax_top.set_title("Top-N Hits", fontsize=13, fontweight="bold")
    annotate_grouped_bars(ax_top, bars_without_top, ["0", "2", "6"])
    annotate_grouped_bars(ax_top, bars_module_top, ["48", "51", "53"])

    x_rank = np.arange(len(rank_metrics))
    bottom = 1.0
    bars_without_rank = ax_rank.bar(
        x_rank - width / 2,
        [value - bottom for value in without_rank],
        width,
        bottom=bottom,
        label="w/o Module Reduction",
        color=PURPLE,
        edgecolor="white",
        linewidth=0.8,
        hatch="//",
    )
    bars_module_rank = ax_rank.bar(
        x_rank + width / 2,
        [value - bottom for value in module_rank],
        width,
        bottom=bottom,
        label="Full Model",
        color=BLUE,
        edgecolor="white",
        linewidth=0.8,
    )
    ax_rank.set_yscale("log")
    ax_rank.set_ylabel("Rank (lower is better, log scale)", fontsize=14, fontweight="bold")
    ax_rank.set_xticks(x_rank)
    ax_rank.set_xticklabels(rank_metrics, fontsize=13, fontweight="bold")
    ax_rank.tick_params(axis="y", labelsize=12)
    ax_rank.set_ylim(1, 10000)
    ax_rank.set_yticks([1, 10, 100, 1000, 10000])
    ax_rank.yaxis.set_major_formatter(plt.ScalarFormatter())
    ax_rank.yaxis.set_minor_formatter(plt.NullFormatter())
    ax_rank.set_title("Average Rank", fontsize=13, fontweight="bold")
    annotate_grouped_bars(ax_rank, bars_without_rank, ["4087.35", "3927.96"])
    annotate_grouped_bars(ax_rank, bars_module_rank, ["25.12", "20.99"])

    handles = [bars_without_top, bars_module_top]
    labels = [handle.get_label() for handle in handles]
    ax_top.legend(handles, labels, loc="upper left", fontsize=9, frameon=True, framealpha=0.9, ncol=1)

    plt.tight_layout()
    save_figure(fig, stem, dpi=300)


def annotate_colored_values(ax: plt.Axes, bars: Iterable[plt.Rectangle], color: str) -> None:
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2.0,
            height + 1.5,
            f"{height:.1f}",
            ha="center",
            va="bottom",
            fontsize=9,
            fontweight="bold",
            color=color,
        )


def plot_rq4_efficiency() -> None:
    methods = ["CLOCAE", "Scaffle", "CrashLocator"]
    data_time = [1.25, 0.51, 0.54]
    rank_time = [5.32, 0.99, 0.02]

    fig, ax = plt.subplots(figsize=(8, 5.5))
    x = np.arange(len(methods))
    width = 0.3

    bars1 = ax.bar(
        x - width / 2,
        data_time,
        width,
        label="Data Collection",
        color="#42A5F5",
        edgecolor="white",
        linewidth=0.8,
    )
    bars2 = ax.bar(
        x + width / 2,
        rank_time,
        width,
        label="Ranking",
        color="#EF5350",
        edgecolor="white",
        linewidth=0.8,
    )

    for bars in (bars1, bars2):
        for bar in bars:
            height = bar.get_height()
            ax.annotate(
                f"{height:.2f}s",
                xy=(bar.get_x() + bar.get_width() / 2, height),
                xytext=(0, 5),
                textcoords="offset points",
                ha="center",
                va="bottom",
                fontsize=10,
                fontweight="bold",
                color="#333333",
            )

    ax.set_ylabel("Time (seconds)", fontsize=14, fontweight="bold")
    ax.set_xticks(x)
    ax.set_xticklabels(methods, fontsize=13, fontweight="bold")
    ax.tick_params(axis="y", labelsize=12)
    ax.set_ylim(0, 6)
    ax.legend(loc="upper right", fontsize=10, frameon=True, framealpha=0.9)

    plt.tight_layout()
    save_figure(fig, "rq4_efficiency", dpi=300)


FIGURES: dict[str, Callable[[], None]] = {
    "rq3_ablation": plot_rq3_ablation,
    "rq3_file_ranking_score": plot_rq3_file_ranking_score,
    "rq3_file_improvement": plot_rq3_file_improvement,
    "rq3_statement_ablation": plot_rq3_statement_ablation,
    "rq3_statement_ranking_score": plot_rq3_statement_ranking_score,
    "rq3_statement_improvement": plot_rq3_statement_improvement,
    "statement_rq3": plot_statement_rq3,
    "statement_ablation": plot_statement_ablation,
    "rq4_efficiency": plot_rq4_efficiency,
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "figures",
        nargs="*",
        help="Figure stem(s) to rebuild. Defaults to all recovered figures.",
    )
    parser.add_argument("--list", action="store_true", help="List available recovered figure stems.")
    args = parser.parse_args()

    if args.list:
        for name in sorted(FIGURES):
            print(name)
        return

    selected = args.figures or ["all"]
    unknown = [name for name in selected if name != "all" and name not in FIGURES]
    if unknown:
        parser.error(f"unknown figure stem(s): {', '.join(unknown)}")

    if "all" in selected:
        selected = list(FIGURES)

    for name in selected:
        FIGURES[name]()


if __name__ == "__main__":
    main()
